### ISSUE TITLE
Custom FindPythonInterp prevents Python 3

### ISSUE THREAD

**Issue by sethrj** [TriBITSPub/TriBITS#148]
I'd like to test out our code with Python 3, but the call made by `FindPythonInterp`

    import sys; print sys.version.split()[0]

is a syntax error in Python 3.0 and higher. Rather than fixing that error (and adding Python 3 versions to that same file), it would be simpler and more future-proof to simply remove the `core/modules/FindPythonInterp.cmake` script and allow the CMake-distributed script (which is more capable than the older version distributed with TriBITS) to take precedence.

**Comment by bartlettroscoe** [comment]
@sethrj, I think @wfspotz added the module [tribits/core/modules/FindPythonInterp.cmake](https://github.com/TriBITSPub/TriBITS/blob/master/tribits/core/modules/FindPythonInterp.cmake) a long time ago (before it got moved to Trilinos/cmake/tribits/ which was then pulled out into this separate TriBITS git repo).  I think @wfspotz did that to better support PyTrilinos but I am not sure. Therefore, I don't know the purpose of the custom module or what it would mean to replace it with the default CMake module.

@sethrj, if you can provide a patch that fixes your issue and post a PR, @wfspotz and I can review it, test it, and then I can push it (and update in CASL and Trilinos).

**Comment by wfspotz** [comment]
I overrode FindPythonInterp.cmake in order to add version checking. It looks like the new version of CMake's standard FindPythonInterp.cmake now supports version checking. We would have to determine at what CMake version this was added and compare that to TriBIT's minimum CMake version requirement.

**Comment by sethrj** [comment]
@wfspotz I can confirm that version checking and setting of `PYTHON_VERSION_STRING` is present in 2.8.12, which is one minor version above `TRIBITS_CMAKE_MINIMUM_REQUIRED`.  The 2.8.12 release notes don't say anything about the FindPythonInterp module being changed so I think it's safe to assume the change was from an older version of cmake.

**Comment by carlos-stellar** [comment]
I'm sure there are other fixes that would need to be applied to the 
file, but the fix for the code sample you provided is trivial:

import sys; print(sys.version.split()[0])

This revised code should behave the same way under both Python 2 and 3.

Carlos Reyes
1-505-206-1569 (mobile)

**Comment by bartlettroscoe** [comment]
> import sys; print(sys.version.split()[0])

@sethrj, can you try this in your local version of TriBITS and see if it fixes your issue?  If it does, can you submit a PR with this fix?

Soon we should try to push to update the minimum-supported version of TriBITS from 2.8.11 to something more recent.  I would say we should push for at least CMake 3.0.0 or newer.  Then we don't need as many if statements for older version of CMake.

**Comment by wfspotz** [comment]
This should have been addressed in the Python 2 -> 3 upgrade we did. I am confused as to why we are seeing it.

**Comment by sethrj** [comment]
@carlos-stellar @bartlettroscoe Yes, that certainly does allow a Python 3.0 executable to be accepted, but the configure failure is only part of the problem.
The `FindPythonInterp` script in TriBITS does not search for python versions greater than 2.7; but more importantly (for our case) it doesn't set the `PYTHON_VERSION_STRING` variable that CMake 2.8.11's version sets.  So if you want to make a configuration requirement that Python 2.7.x be the maximum version (for projects that don't support Python 3), or if you want to make other configuration changes (e.g. adding the `-py3` flag to SWIG) only when Python 3 is enabled, the downstream users will have to re-implement the version detection code that's already been put into CMake's `FindPythonInterp`.

I think simply removing the script is a far simpler and better solution.

**Comment by bartlettroscoe** [comment]
Then we have to update the minimum version to cmake 2.8.12, right?

**Comment by sethrj** [comment]
@bartlettroscoe I downloaded 2.8.11 and verified it has all the Python version checking logic present in the current version and more recent than the TriBITS version. So removing FindPythonInterp will not require a change in the minimum CMake version.

**Comment by bartlettroscoe** [comment]
@sethrj, I am fine with PR #148.  My only worry is that it will break PyTrilinos under Trilinos.  I am not set up to be able to build and test PyTrilinos so I will need some help testing it.  Also, it appears that there is no automated testing set up for PyTrilinos as shown here:

* http://testing.sandia.gov/cdash/viewSubProjects.php?project=Trilinos&date=2016-10-12

so if we do break it, we will never know.

@wfspotz, if you want to make sure that this change will not break PyTrilinos, then can you please try out building Trilinos with this version of TriBITS with PyTrilinos enabled with Python 2.6+ and 3.0+ and see what happens?

Otherwise, I think it seems pretty safe for me to test this branch in #148 locally and push and then if it does break PyTrilinos it can be fixed after the fact.  Since this should not result in any new Trilinos build/test failures since PyTrilinos is not being tested, that seems reasonable to me.

**Comment by bartlettroscoe** [comment]
I accepted PR #149 by rebasing and editing the commits (to add the GitHub ID and requested here and then tested as pushed as the commits 36fd6cf and b3be5c7. I am closing this PR.

@sethrj, do you need this synced to the CASL VERA TriBITS clone or is having it pushed to the 'master' branch of this GitHub repo enough?  It will get synced to CASL and Trilinos eventually.

Let me know if it is okay to close this Issue.

**Comment by bartlettroscoe** [comment]
No response to above comment so closing as complete.

**Comment by bartlettroscoe** [comment]
@bmpersc says that this update changed the way that Python is found.  Instead of finding the first version of Python that has the minimum version of 2.6 it instead finds the the first Python that is exactly that version.  This is breaking the current Trilinos CI build in that it skips over the first Python in the path that is 2.7 and instead finds the 2.6 which is deeper in the path.  That breaks some other TPLs that are used that are built using Python 2.7.

Is there a way to change this back to finding an **minimum** version of Python instead of the exact version?  Can we change this to find Python versions in the order 3.x, 2.7, 2.6, etc.?

**Comment by bartlettroscoe** [comment]
CC: @jwillenbring 

@bmpersc, I am not seeing the behavior you described on the phone just now for the TribitsCTestDriverCore.cmake code with Python.  For Trilinos version:

```
1b14dad "Turn off ST code and set test categories to BASIC (#482)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Nov 29 06:42:11 2016 -0700 (3 hours ago)

M       cmake/ctest/drivers/sems_ci/ctest_linux_mpi_debug_shared_pt_ci.sems.cmake
```

I see:

```
DRIVER_SCRIPT_DIR = './Trilinos/cmake/ctest/drivers/sems_ci'
TRILINOS_DIR='/home/rabartl/Trilinos.base/SEMSCIBuild/Trilinos'
BASE_COMMAND = './Trilinos/cmake/ctest/drivers/sems_ci/single_ci_iter.sh'
LOOP_INTERVAL = '3m'
TODAY_RUN_TILL = '23:59:00'
PAUSE_FILE = '/ascldap/users/rabartl/Trilinos.base/SEMSCIBuild/pause_ci_server.txt'
echo "Message:  Starting Trilinos standrad CI testing server on 'crf450.srn.sandia.gov'
Machine:  crf450.srn.sandia.gov
PWD:      /home/rabartl/Trilinos.base/SEMSCIBuild" | mailx -s "Starting Trilinos standrad CI testing server on 'crf450.srn.sandia.gov'" rabartl@sandia.gov
DRIVER_SCRIPT_DIR = './Trilinos/cmake/ctest/drivers/sems_ci'
TRILINOS_DIR='/home/rabartl/Trilinos.base/SEMSCIBuild/Trilinos'

*******************************
*** TribitsCTestDriverCore ***
*******************************

TRIBITS_PROJECT_ROOT = '/ascldap/users/rabartl/Trilinos.base/SEMSCIBuild/Trilinos'
PROJECT_NAME = Trilinos
Trilinos_TRIBITS_DIR = /ascldap/users/rabartl/Trilinos.base/SEMSCIBuild/Trilinos/cmake//tribits
Set default for CTEST_SOURCE_DIRECTORY to TRIBITS_PROJECT_ROOT='TRIBITS_PROJECT_ROOT='/ascldap/users/rabartl/Trilinos.base/SEMSCIBuild/Trilinos'
Set defualt for CTEST_BINARY_DIRECTORY to $PWD/BUILD='/ascldap/users/rabartl/Trilinos.base/SEMSCIBuild/BUILD'
-- Found PythonInterp: /projects/sems/install/rhel6-x86_64/sems/compiler/python/2.7.9/bin/python (found suitable version "2.7.9", minimum required is "2.6") 
PYTHON_EXECUTABLE = /projects/sems/install/rhel6-x86_64/sems/compiler/python/2.7.9/bin/python
...
```

See, it recognizes that the minimum is 2.6 but it actually finds 2.7.  I know that 2.6 is in the path because it is in /usr/bin:

```
$ /usr/bin/python --version
Python 2.6.6
```

I am just going to watch this and see what happens but it looks like it is okay so far.

@bmperc, can you create a Trilinos JIRA issue for this if you see this again.  Otherwise, I am going to assume this issue is fixed.
