### ISSUE TITLE
don't install tribits files

### ISSUE THREAD

**Issue by nschloe** [TriBITSPub/TriBITS#168]
Right now, when installing Trilinos, a whole bunch of TriBITS files are installed under
```
/prefix/lib/cmake/tribits/
```
Are those really necessary? If not, I would suggest not installing them.

**Comment by bartlettroscoe** [comment]
These are necessary for xSDKTrilinos to build as an independent CMake project.  However, a client can choose to not install them by setting the **Trilinos** configure option `-DTrilinos_INSTALL_TriBITS=OFF` (you can see this advanced variable defined in the CMake Cache file).

But note that TriBITS is not installing anything, Trilinos is.  TriBITS does not have offical support for installing itself yet.  See #114.

Since this is not really a TriBITS issue, per-say, but a Trilinos issue, I am closing as invalid.

**Comment by nschloe** [comment]
> These are necessary for xSDKTrilinos to build as an independent CMake project.

I don't understand. If Trilinos is configured and installed with `-DTrilinos_INSTALL_TriBITS=OFF`, what exactly won't be working?

**Comment by bartlettroscoe** [comment]
> I don't understand. If Trilinos is configured and installed with -DTrilinos_INSTALL_TriBITS=OFF, what exactly won't be working?

The CMake project xSDKTrilinos:

* https://github.com/trilinos/xSDKTrilinos

requires TriBITS to be installed by Trilinos in order for it to configure and build.   This is critical for the xSDK:

* https://github.com/xsdk-project/installxSDK

**Comment by nschloe** [comment]
Ah, I thought xSDK was some sort of sophisticated wrapper script that downloads SuperLU, Trilinos, PETSc etc. and installs all of those things. Never knew that it could _use_ an existing Trilinos installation.
