### ISSUE TITLE
an empty TPLs list causes an error when the list is reversed

### ISSUE THREAD

**Issue by wawiesel** [TriBITSPub/TriBITS#170]
Here's the diff

```
$ git diff
diff --git a/tribits/core/package_arch/TribitsWriteClientExportFiles.cmake b/tribits/core/package_arch/TribitsWriteClientExportFiles.cmake
index 6429dae..b8a64a0 100644
--- a/tribits/core/package_arch/TribitsWriteClientExportFiles.cmake
+++ b/tribits/core/package_arch/TribitsWriteClientExportFiles.cmake
@@ -691,8 +691,10 @@ FUNCTION(TRIBITS_WRITE_PROJECT_CLIENT_EXPORT_FILES)

   # Reversing the tpl list so that the list of tpls will be produced in
   # order of most dependent to least dependent.
-  SET(TPL_LIST ${${PROJECT_NAME}_TPLS})
-  LIST(REVERSE TPL_LIST)
+  IF( ${${PROJECT_NAME}_TPLS} )
+    SET(TPL_LIST ${${PROJECT_NAME}_TPLS})
+    LIST(REVERSE TPL_LIST)
+  ENDIF()

   # Loop over all TPLs to determine which were enabled. Then build a list
   # of all their libraries/includes in the proper order for linking
```

**Comment by bartlettroscoe** [comment]
This must be a use case that is not being covered in automated testing for TriBITS.  What is the full context for this error? What CMake project is being used to generate this error?

In any case, I will try to add an automated test to reproduce this failure.

**Comment by bartlettroscoe** [comment]
@wawiesel,

I just pushed a fix to the 'master' branch in this repo (as of commit ac30fbb).   I updated the "TribitsHelloWorld" test to reproduce this problem (that project/repo has no TPLs) and cherry-picked your commit 3db123c.  However, the change broke TriBITS for cases where there were TPLs.  The fix was simple, I just replaced `IF (${${PROJECT_NAME}_TPLS})` with `IF (${PROJECT_NAME}_TPLS)` and that did it.

I also fixed this code to work for when no Version.cmake file is given.  In this case, it will set the version as 0.0.0 (which seems reasonable if there is not version set).

Please pull the updated 'master' branch and verify this works for you.

**Comment by bartlettroscoe** [comment]
Assuming this is fixed and closing.
