### ISSUE TITLE
Fortran .mod files support

### ISSUE THREAD

**Issue by aprokop** [TriBITSPub/TriBITS#178]
I'm trying to figure out how to use Fortran with Tribits for the ForTrilinos project. I have the following subpackage structure in place:
.
├── simple
│   ├── cmake
│   ├── src
│   └── test
└── teuchos
    ├── cmake
    ├── src
    └── test

The src/ directories contain module .f90 files. During the build, they generate .mod files which are stored in the binary src/ directories. The problem is that when compiling simple/ tests I need access to teuchos .mod files which are in teuchos' binary directory /src. Is there a way to include that directory based on subpackage dependencies without hardcoding it?

**Comment by bartlettroscoe** [comment]
@aprokop,

Is this the real "teuchos" package directory?  There are no Fortran files in the real Teuchos that I can find:

```
[rabartl@crf450 Trilinos (develop)]$ find packages/teuchos -name "*.F*"
[rabartl@crf450 Trilinos (develop)]$ find packages/teuchos -name "*.f*"
```

In any case, you need to call:

```
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})
```

**before** the call the `TRIBITS_ADD_LIBRARY()` so that those include dirs will be transferred to the build lines for downstream package libraries.  That will cause the `-I` include dir for the directory where the upstream `*.mod` files are created to be found in downstream compiles.  Does that make sense?

Is ForTrilinos just an add-on TriBITS Repo and Package like DataTransferKit as described at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#coexisting-projects-repositories-and-packages

?

If so, it would be easy for me to pull this and try it out with Trilinos if you would like.

**Comment by aprokop** [comment]
No, this is not a real `teuchos` directory, it is a `teuchos` directory in ForTrilinos.

The code is available in this PR: trilinos/ForTrilinos#14.

So, if I understand correctly, if I call `INCLUDE_DIRECTORIES($CMAKE_CURRENT_BINARY_DIR)` it would add this directory to the list of `-I` directories that would automatically added when compiling all packages that depend on this one, right?

I'll try it out and let you know.

**Comment by aprokop** [comment]
@bartlettroscoe Ross, that worked, thank you!

**Comment by bartlettroscoe** [comment]
@aprokop,

I updated the section:

* https://tribits.org/doc/TribitsDevelopersGuide.html#include-directories-tribits-add-library

to hopefully help to answer this question in the future for people wondering how to handle Fortran *.mod files.  Can you take a quick look and see if that would have answered your question?

**Comment by aprokop** [comment]
LGTM.
