### ISSUE TITLE
TRIBITS_CTEST_DRIVER ignores ENABLE_ALL_OPTIONAL_PACKAGES option

### ISSUE THREAD

**Issue by mplooster** [TriBITSPub/TriBITS#195]
When using the TRIBITS_CTEST_DRIVER() macro, it is possible to first set CMake variables and/or configure options to enable optional packages. Using Trilinos as an example:

`SET(Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES OFF)`
`SET(EXTRA_SYSTEM_CONFIGURE_OPTIONS "-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF")`
`...`
`TRIBITS_CTEST_DRIVER()`

However, this option is ignored because in TribitsCTestDriverCore.cmake, [line 871](https://github.com/TriBITSPub/TriBITS/blob/1957aa426f27e819c3b6e78fdeb3811f6994b0ef/tribits/ctest_driver/TribitsCTestDriverCore.cmake#L871) and [line 1000](https://github.com/TriBITSPub/TriBITS/blob/1957aa426f27e819c3b6e78fdeb3811f6994b0ef/tribits/ctest_driver/TribitsCTestDriverCore.cmake#L1000) its value is hard-coded to be ON. Even if the variable is set in EXTRA_SYSTEM_CONFIGURE_OPTIONS, it is only **appended** to the CONFIGURE_OPTIONS on [line 1038](https://github.com/TriBITSPub/TriBITS/blob/1957aa426f27e819c3b6e78fdeb3811f6994b0ef/tribits/ctest_driver/TribitsCTestDriverCore.cmake#L1038), which results in a duplication of the configure options, like this:

`"-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON"`
`"-DTrilinos_ENABLE_TESTS:BOOL=Epetra_ENABLE_TESTS"`
`...`
`"-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF"`

During the configure phase of the ctest driver, the first option is respected while the second is ignored (tested on Windows).

One possible fix might be to use SET_DEFAULT to set the value of the CMake variable ${PROJECT_NAME}_ENABLE_ALL_OPTIONAL_PACKAGES on line 871, and then use the value of this variable when setting the configure options on line 1000.

**Comment by bartlettroscoe** [comment]
Thanks for reporting this.  I will take a look shortly.  I can test this after I have completed #193, where I just added a bunch of more strong automated tests for TribitsCTestDriverCore.cmake so this is good timing.

**Comment by bartlettroscoe** [comment]
Given the current way that package-by-package testing works, I am not sure it is a good idea to be disabling `${PROJECT_NAME}_ENABLE_ALL_OPTIONAL_PACKAGES`.  That this would do is to make it so that every package tested (one-by-one) would only be tested by its **required** upstream packages and none of its **optional** upstream packages.  I think that one such automated build on one platform of a project like Trilinos that only enables optional upstream packages one-by-one is not a bad idea but I don't think that is a good idea for 99% of the other builds.

In trilinos/Trilinos#1160 I asked about the underlying use case for a Windows build that is supposed to be driving this.  I suspect that what is really needed for that build is not the behavior you would get by setting `${PROJECT_NAME}_ENABLE_ALL_OPTIONAL_PACKAGES=OFF`.

I think, if nothing else, at least the TribitsCTestDriverCore.cmake code should print out a warning if the user tries to set `${PROJECT_NAME}_ENABLE_ALL_OPTIONAL_PACKAGE=OFF` and explain that it is being ignored and why it is being ignored.  Either that, or it should just `FATAL_ERROR` out if it detects the user is trying to set this.

Again, if a project like Trilinos ever really wants to set up a package-by-package build of only required dependencies, then I think we can allow the user to set `${PROJECT_NAME}_ENABLE_ALL_OPTIONAL_PACKAGES=OFF`.  But until then, I don't see any valid use case were you would want to do this with any project that I know about.

Note that once we implement #183, then it would be fine to set `${PROJECT_NAME}_ENABLE_ALL_OPTIONAL_PACKAGES=OFF` and explicitly list the packages you want to enable.  But that is not supported yet (and may not be for some time).

**Comment by bartlettroscoe** [comment]
This question was answered [above](https://github.com/TriBITSPub/TriBITS/issues/195#issuecomment-305068242) 20 months ago.  In any case, the new all-at-once mode addresses this issue once and for all.
