### ISSUE TITLE
TribitsDriverDashboard.cmake trying to include missing file

### ISSUE THREAD

**Issue by william76** [TriBITSPub/TriBITS#211]
@bartlettroscoe 

The Trilinos 12.12 Release testing is failing due to an apparent error in the tribits CMake scripts:
[https://testing.sandia.gov/cdash/index.php?project=Trilinos##Nightly_Release_12.12](https://testing.sandia.gov/cdash/index.php?project=Trilinos##Nightly_Release_12.12)

This is in the output log from CMake on jenkins:
```
22:56:22 ***
22:56:22 *** TribitsDriverDashboard.cmake
22:56:22 ***
22:56:22 
22:56:22 TRIBITS_ROOT = '/jenkins/slave/workspace/Trilinos_hansel_release_12.12/Trilinos/cmake/tribits'
22:56:22 TRIBITS_CMAKE_UTILS_DIR = '/jenkins/slave/workspace/Trilinos_hansel_release_12.12/Trilinos/cmake/tribits/core/utils'
22:56:22 CMake Error at Trilinos/cmake/tribits/dashboard_driver/TribitsDriverDashboard.cmake:70 (INCLUDE):
22:56:22   include could not find load file:
22:56:22 
22:56:22     /jenkins/slave/workspace/Trilinos_hansel_release_12.12/Trilinos/cmake/tribits/dashboard_driver/../ctest_driver/TribitsUpdateExtraRepo.cmake
```

followed by this a bit later:
```
22:58:28 *** Finished TribitsDriverDashboard.cmake ***
22:58:28 
22:58:28 Error in read script: /jenkins/slave/workspace/Trilinos_hansel_release_12.12/Trilinos/cmake/tribits/dashboard_driver/TribitsDriverDashboard.cmake
22:58:28 
22:58:28   Runtime for command = 2.103829 minutes
22:58:28 ctestRtn: '255'
22:58:28 error: ctest returned non-zero error value, script will exit with 255
```

It looks like ```tribits/dashboard_driver/TribitsDriverDashboard.cmake``` includes ```tribits/ctest_driver/TribitsUpdateExtraRepo.cmake``` on line 70:
```
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/../ctest_driver/TribitsUpdateExtraRepo.cmake)
```
but commit 61949ddf430de64c1c3d1c1ef511f28c959a1361 removed this file.  From what I can tell, that file defined a macro and 2 functions:
1. MACRO(EXTRAREPO_EXECUTE_PROCESS_WRAPPER)
2. FUNCTION(EXTRAREPO_GET_TRACKING_BRANCH ...)
3. FUNCTION(EXTRAREPO_CLEAN_FETCH_RESET ...)

It looks like (1) and (2) were moved into ```tribits/ctest_driver/TribitsCTestDriverCoreHelpers.cmake``` and (3) was deleted because I can't find it.  There is a call to it in ```tribits/dashboard_driver/TribitsDriverDashboard.cmake``` though.

It also appears that (1) is defined twice in ```tribits/ctest_driver/TribitsCTestDriverCoreHelpers.cmake```, on lines 45, and 136.  They look identical but I didn't look too closely to see if there is anything different between the two.

FYI @jwillenbring @bmpersc

**Comment by bartlettroscoe** [comment]
Sorry, just saw this (did not get a GitHub notification email) ...

That is strange.   Why does this system work on the 'develop' branch of Trilinos and not on this release branch?  For example, we can see there are still TriBITS Dashboard Driver builds submitting to the TrilinosDriver project:

* https://testing.sandia.gov/cdash/index.php?project=TrilinosDriver&date=2017-07-31

Given that this is working on the Trilinos 'develop' branch, you might just snapshot cmake/tribits/ from the 'develop' branch to that release branch and try that.

**Comment by bmpersc** [comment]
@bartlettroscoe both the Trilinos develop branch and the 12.12 release branch have the same version of Tribits. Both are at this commit: "Automatic snapshot commit from tribits at 17dc675."

**Comment by bartlettroscoe** [comment]
> both the Trilinos develop branch and the 12.12 release branch have the same version of Tribits. Both are at this commit: "Automatic snapshot commit from tribits at 17dc675."

That is strange.  Why is it working on 'develop' and not on this release branch?  Again, how is it that we see TriBITS Dashboard Driver builds showing up at:

* https://testing.sandia.gov/cdash/index.php?project=TrilinosDriver&date=2017-07-31

if the same version of TriBITS is being used in both?

But I will look into this and see if there is an easy fix.  But I may not test the TriBITS Dashboard Driver (since it is very hard to do).

In any case, as I have said before, I want to abandon the old TriBITS Dashboard Driver system (created by a contractor) and start over with something much simpler.  All we need is a simple CMake project and CTest -S driver that uses ADD_TEST() in the inner CMake project to run some `ctest -S <script>` scripts in parallel and time them out if needed.  I just a need a day or so to put that together (but I can't get to that for a while and that would not impact this release of Trilinos).

**Comment by bartlettroscoe** [comment]
@william76 and @bmpersc,

I just pushed the commits:

```
dab74e0 "Merge branch 'fix-tdd-tribits-211' into trilinos-release-12-12-branch"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Aug 1 18:08:25 2017 -0600 (4 minutes ago)

60f3f96 "Automatic snapshot commit from tribits at 839eef0"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Aug 1 18:06:02 2017 -0600 (6 minutes ago)

M       cmake/tribits/ctest_driver/TribitsCTestDriverCoreHelpers.cmake
M       cmake/tribits/dashboard_driver/TribitsDriverDashboard.cmake
```

to the Trilinos branch `trilinos-release-12-12-branch`.  There is a good chance this will fix the issue.  You can test it locally without having to submit using the instructions in the file Trilinos/cmake/tribits/ctest_driver/README (file written by contractor originally and I modified some since).

If this does not work, please let me know and I will find a way to test this locally and get this fixed.

**Comment by bartlettroscoe** [comment]
Judging from the fact that Trilinos Release 12.12 builds have been posting to CDash for a while (see #215), I am going to close this as resolved.

In the future, people should stop using the TriBITS Dashboard Driver System.  For the Trilinos ATDM builds, I throw together some very simple Jenkins drivers that just clone and update Trilinos twice for each build.  It is working very nicely.
