### ISSUE TITLE
Testcases fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [TriBITSPub/TriBITS#252]
```
179/263 Test #189: TriBITS_TribitsExampleProject_SimpleTpl_RPATH_CMAKE_SKIP_INSTALL_RPATH_run ..............................***Not Run   0.00 sec
        Start 190: TriBITS_TribitsExampleProject_ProjectCompilerPostConfig
        Start 191: TriBITS_TribitsExampleProject_TribitsExampleProjectAddons
180/263 Test #169: TriBITS_TribitsExampleProject_ALL_ST_NoFortran ..........................................................***Failed  Required regular expression not found.Regex=[OVERALL FINAL RESULT: TEST PASSED .TriBITS_TribitsExampleProject_ALL_ST_NoFortran.
] 28.17 sec
...
The following tests FAILED:
	169 - TriBITS_TribitsExampleProject_ALL_ST_NoFortran (Failed)
	178 - TriBITS_TribitsExampleProject_WrapExternal (Failed)
	179 - TriBITS_TribitsExampleProject_ALL_NoFortran_WrapExternal_VerboseConfigure (Failed)
	180 - TriBITS_TribitsExampleProject_ALL_NoFortran_OverridePackageSourceDir (Failed)
	188 - TriBITS_TribitsExampleProject_SimpleTpl_RPATH_no_SET_INSTALL_RPATH_run (Not Run)
	189 - TriBITS_TribitsExampleProject_SimpleTpl_RPATH_CMAKE_SKIP_INSTALL_RPATH_run (Not Run)
```

**Comment by bartlettroscoe** [comment]
Any details on why these are failing?   Can you attach the contents of the `<build-dir>/Testing/Temporary/LastTest.log` file?

Note that some of these tests are very strong (in terms of what they check) but it has been hard to make all of these tests portable because they seem to depend on behavior that changes from system to system (in ways that I have not been able to predict).  For example, how to inspect the generated binaries to make sure that the right RPATH is set has been hard to make portable but is critical from a validation perspective.

**Comment by bartlettroscoe** [comment]
No response to my response [above](https://github.com/TriBITSPub/TriBITS/issues/252#issuecomment-372183720) in 10 months.  Closing as invalid.

**Comment by bartlettroscoe** [comment]
No response to my response above in 10 months. Closing as invalid.
