### ISSUE TITLE
gitdist:  Create Table of SHA1s

### ISSUE THREAD

**Issue by jmgate** [TriBITSPub/TriBITS#286]
> **Note:**  @bartlettroscoe, I'm just writing up this issue to remind myself to tackle it at some point.

When having users/developers report bugs, or having developers report how they've tested a PR, we'd like to have people fill out a table of SHA1s so we know exactly where things are going wrong or how things were tested.  This looks something like
```
| Repo1   | Repo2   | ... | RepoN   |
|:-------:|:-------:|:---:|:-------:|
| insert  | sha1s   | ... | here    |
```

The problem is this requires people do something like `gitdist rev-parse --short HEAD` and then copy the SHA1s individually into the table in the issue/PR template.  It'd be really nice if instead they could just `gitdist dist-sha1-table` (or something along those lines) and have it spit out the Markdown table so they could just select it, copy, and paste.

**Comment by bartlettroscoe** [comment]
@jmgate, for this purpose,  I usually just attach the `<Project>RepoVersion.txt` file](https://tribits.org/doc/TribitsDevelopersGuide.html#gitdist-dist-help-repo-versions) which looks like:

```
  *** Base Git Repo: BaseRepo
  e102e27 [Mon Sep 23 11:34:59 2013 -0400] <author0@someurl.com>
  First summary message
  *** Git Repo: ExtraRepo1
  b894b9c [Fri Aug 30 09:55:07 2013 -0400] <author1@someurl.com>
  Second summary message
  *** Git Repo: ExtraRepo1/ExtraRepo2
  97cf1ac [Thu Dec 1 23:34:06 2011 -0500] <author2@someurl.com>
  Third summary message
  *** Git Repo: ExtraRepo3
  6facf33 [Fri May 6 15:28:35 2013 -0400] <author3@someurl.com>
  Fourth summary message
  ...
```

What is nice about that is that it gives more context than just SHA1s.  And anyone can download that to a file to checkout that exact version with:

```
$ cd <base-repo>/
$ gitdist --dist-version-file=~/<Project>RepoVersion.<date>.txt checkout _VERSION_
```

or just look at commits between two such versions, etc.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#gitdist-dist-help-repo-versions

Is EMPIRE not using an `EMPIRERepoVersion.txt` file?

One nice thing to do would be to simplify the generation of these files by adding a [`gitdist dist-repo-version` command](https://docs.google.com/document/d/1WKs8rJhI3037yKGnEVMhIx9dPN7a7uFRM5isdNAhAXI/edit#heading=h.r13i2iz05m8l).

If we do provide a table like this, I would be a little worried about having the repos go across the top columns like:

```
| Repo1   | Repo2   | ... | RepoN   |
|:-------:|:-------:|:---:|:-------:|
| insert  | sha1s   | ... | here    |
```

since that would not scale well for many repos.  The CASL VERA project which uses gitdist, for example, has more than 20 git repos so that table would not fit in a GitHub/Gitlab issue.  I think gitdist scales nicely to O(20) repos or so if we want to produce a table, it might be better if it is row oriented something like:

```
| Repo Dir | SHA1 | Commit Date | Author | Summary |
| :-- | :-- | --: | :-- | :-- |
...
```

**Comment by jmgate** [comment]
> if we want to produce a table, it might be better if it is row oriented something like

This sounds like a good idea.

**Comment by bartlettroscoe** [comment]
@jmgate,

PR #287 is merged to TriBITS 'master' (Thanks!) and Trilinos PR trilinos/Trilinos#6251 will update `gitdist` in Trilinos as well.

Please let me know if we can close this issue.

Thanks!
