### ISSUE TITLE
How to set up a TriBITS project from scratch

### ISSUE THREAD

**Issue by mayrmt** [TriBITSPub/TriBITS#354]
## Context

I'm trying to setup a build system for a new multi-package and probably multi-repository software project. Hence, I opted for TriBITS as build system. 

## Question

Is there a step-by-step manual to setup a TriBITS project from scratch? I've extensively read through the TriBITS developer guide. From that, I have understood which files (`CMakeLists.txt`, `ProjectName.cmake`, ...) need to be provided.

My question is rather related to the TriBITS installation. I guess that I need to provide a TriBITS installation on my machine, such that it can be used by any software project. However, how to install TriBITS? I saw the `three steps (git clone` -- `do-configure` -- `make`) in the TriBITS top-level README, when developing TriBITS. However, I want to use it in user applications.

I'm aware that Trilinos comes with TriBITS as part of the Trilinos repository and that Trilinos installs TriBITS, but I'd like to understand how to install TriBITS on my machine independent of Trilinos.

- Is there any documentation on that, that I have missed so far?
- What are the necessary steps?

**Comment by mayrmt** [comment]
After I've understand the installation process, I can imagine to add TriBITS as a package to `spack` (spack.io) to automate the install process. Therefore, TriBITS would need to provide some kind of version identifier. So far, I haven't found any releases or tags.

**Comment by bartlettroscoe** [comment]
Hello @mayrmt,

> Is there a step-by-step manual to setup a TriBITS project from scratch? 

Not really.  There was an attempt to start a tutorial a couple of years ago by someone else but that did not go very far.  The best tutorial for the basics is to just look at the example TriBITS projects as per:

* https://tribits.org/doc/TribitsDevelopersGuide.html#example-tribits-projects

I would start with TribitsExampleProject:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribitsexampleproject

**Comment by mayrmt** [comment]
@bartlettroscoe Thanks for these hints! Is my assumption, that I have to install TriBITS before using it in any project correct?

**Comment by bartlettroscoe** [comment]
> Therefore, TriBITS would need to provide some kind of version identifier. So far, I haven't found any releases or suitable tags.

> Is my assumption, that I have to install TriBITS before using it in any project correct?

@mayrmt, TriBITS has never put out official releases because all projects that have used TriBITS in the past have either snapshotted TriBITS into their source tree (see [10.18   TriBITS directory snapshotting](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-directory-snapshotting)) (e.g. Trilinos, MPACT, CTF, etc.), or gotten TriBITS from Trilinos (e.g. Charon2, Drekar, etc.), or kept their own clone of Trilinos (e.g. VERA).  In all of these cases, the customers have used upgrades on an as-needed basis (much like almost all internal customers of Trilinos get Trilinos upgrades).

Note that TriBITS Core is currently about 1.3M is since so it has typically been a small overhead to snapshot TriBITS into the customer projects source compared to the size of the source trees for the projects that might use it.  Even the little independent Kokkos package is 31M so adding another 1M for TriBITS would be a drop in the bucket.

But if there is a desire to pre-install TriBITS and use version numbering, then I think we can support that pretty easily.  To do that, we should consider working #114 and put out version 0.1.0 (compatible with semver.org).   That is not a lot of work if you are interested in that.

@mayrmt, if you don't mind, it might be good to talk through your planned usage of TriBITS and how it might be impacted by the big refactorings of #63 and #299 that are immanent.  That work may impact how you are planning to use TriBITS.

**Comment by mayrmt** [comment]
@bartlettroscoe Snapshotting TriBITS into the source tree is ok for me. I was aware of this scenario from Trilinos, but I wasn't aware of its simplicity.

I'll have to study #63 and #299 and talk to some colleagues before I can make a sound statement on that. I'll get back to you later. 

Thanks again for the immediate help!

**Comment by bartlettroscoe** [comment]
@mayrmt, where are you with this?  Do we need to keep this GitHub Issue open or do you have what you need?

**Comment by mayrmt** [comment]
@bartlettroscoe Thanks for checking in. Most of my basic questions have been answered. I haven't found time to coordinate with all team members and to really get started on using TriBITS the way I intended. So, I close this for now and will reopen if/when further questions arise.
