### ISSUE TITLE
Request: more fine-grained installation options

### ISSUE THREAD

**Issue by sethrj** [TriBITSPub/TriBITS#55]
This is more of "wish list" than an issue, but it would be nice to have a configure-time option to globally disable the installation of header files. Copying thousands of header files on slow file systems such as Lustre® is annoying and typically unnecessary.

This would probably mean writing another TRIBITS wrapper for `INSTALL(FILES ... )`, but being able to differentiate between installing headers (only needed if this particular installation is treated as a library) or binaries/shared libraries/python packages (needed for end user installations).

Writing an install macro could also allow the header commands to be simplified from the error-prone

    FILE(GLOB HEADERS *.hh)
    LIST(APPEND HEADERS ${CMAKE_CURRENT_BINARY_DIR}/config.h)
    INSTALL(FILES
        ${HEADERS}
        DESTINATION include/package/subpackage)

to

    TRIBITS_INSTALL_HEADERS( *.hh )

assuming it knows about config.h from the `TRIBITS_CONFIGURE_FILE` command, and that the destination base path is always `include`, and that headers belong in `package/subpackage`.

**Comment by bartlettroscoe** [comment]
This is something that we need for packages that don't install headers into the flat directory tree.

Noe that headers that are installed into the flat directory `${${PROJECT_NAME}_INSTALL_INCLUDE_DIR}/` that are passed into `TRIBITS_ADD_LIBRARY()` can already by excluded as described [here](https://tribits.org/doc/TribitsDevelopersGuide.html#install-targets-tribits-add-library) when `{PROJECT_NAME}_INSTALL_LIBRARIES_AND_HEADERS=FALSE` is set.

To address another request #51, we should do this with:

```
TRIBITS_ADD_HEADERS(
  [HEADERS <h0> <h1> ...]
  [NOINSTALLHEADERS <nih0> <hih1> ...]
  [INSTALL_SUBDIR <subdir>]
  )
```

Here, `<subdir>` would be relative to `${${PROJECT_NAME}_INSTALL_INCLUDE_DIR}/`, **not** `${CMAKE_INSTALL_PREFIX}/`.  However, absolute paths would be respected if specified.

Note that if a library were only installing headers into a single subdir, we could also add the argument:

```
  HEADER_INSTALL_SUBDIR  <header_subdir>
```
to the function `TRIBITS_ADD_LIBRARY()`.

Take a look at #51 and tell me if this would satisfy your needs.




That woul

**Comment by bartlettroscoe** [comment]
Seth, I just pushed commits to the TriBITS 'master' branches on the github and casl-dev repos adding a new function [TRIBITS_INSTALL_HEADERS())(https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-install-headers) and I added the argument `HEADERS_INSTALL_SUBDIR` to [TRIBITS_ADD_LIBRARY()](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-add-library).  You can use these to remove all of the raw `INSTALL()` commands in the various SCALE and Exnihilo CMakeLists.txt files:

```
[8vt@u235 SCALE (master)]$ find . -name CMakeLists.txt -exec grep -li "install[(]" {} \; | wc -l
142
```
The reason this is important is to make sure the headers get installed in the right directory according to the location defined by the [TriBITS project setting](https://tribits.org/doc/TribitsBuildQuickRef.html#setting-the-install-prefix-at-configure-time) and so we can [skip installing the headers when installing executables](https://tribits.org/doc/TribitsBuildQuickRef.html#avoiding-installing-libraries-and-headers) (see [${PROJECT_NAME}_INSTALL_LIBRARIES_AND_HEADERS](https://tribits.org/doc/TribitsDevelopersGuide.html#project-name-install-libraries-and-headers)).

Let me know if you have any questions.  Otherwise, I am putting this story [in review](https://github.com/TriBITSPub/TriBITS/wiki/Kanban-Process-for-Issue-Tracking).

If there is a particular convention that SCALE and/or Exnihilo packages want to use to define how to install header files, then you can write your own CMake function to call `TRIBITS_INCLUDE_HEADERS()` to simplify things, like you described in the initial description of this Issue ticket.

**Comment by bartlettroscoe** [comment]
Seth, I am going to assume this is working for you and close this Story.
