### ISSUE TITLE
TRIBITS_ADD_EXECUTABLE_AND_TEST Option TIMEOUT

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#65]
The TIMEOUT option for function TRIBITS_ADD_EXECUTABLE_AND_TEST does not work.
It works for TRIBITS_ADD_TEST, but appears to be ignored with the compound function.

**Comment by bartlettroscoe** [comment]
There should be excellent unit tests that prove that it does and we rely on this in CASL VERA and we observe that it does work.   How can I reproduce the behavior you are seeing?

**Comment by lefebvre** [comment]
Ross,

This example works where ${FTESTS} is a list of fortran unit tests:
--------------------------------------------------------------------------------------------
FOREACH(test ${FTESTS})

  GET_FILENAME_COMPONENT(name ${test} NAME_WE)
  TRIBITS_ADD_EXECUTABLE(${name}
    SOURCES ${test}
    COMM serial
    LINKER_LANGUAGE Fortran
    TESTONLYLIBS ${PACKAGE_NAME}_test_fortran_lib
  )
  TRIBITS_ADD_TEST(${name}
    SOURCES ${test}
    COMM serial
    TIMEOUT 300
  )
ENDFOREACH()
--------------------------------------------------------------------------------------------
This example fails:
--------------------------------------------------------------------------------------------
FOREACH(test ${FTESTS})

  GET_FILENAME_COMPONENT(name ${test} NAME_WE)
  TRIBITS_ADD_EXECUTABLE_AND_TEST(${name}
    SOURCES ${test}
    COMM serial
    LINKER_LANGUAGE Fortran
    TESTONLYLIBS ${PACKAGE_NAME}_test_fortran_lib
    TIMEOUT 300
  )
ENDFOREACH()
--------------------------------------------------------------------------------------------

**Comment by bartlettroscoe** [comment]
Jordan, as we discovered in your office, this is indeed a defect in the handling of the args in TRIBITS_ADD_EXECUTABLE_AND_TEST().  The issue is that the parsing code was handling TIMEOUT as a option (with no arguments) instead of as an argument.  My unit test played along and tested:

```
  TRIBITS_ADD_EXECUTABLE_AND_TEST(
    execName
    ...
    ENVIRONMENT env1=envval1 env2=envval2
    WILL_FAIL
    TIMEOUT
    ADDED_EXE_TARGET_NAME_OUT execName_TARGET_NAME
    ADDED_TESTS_NAMES_OUT execName_TEST_NAME
    )
```
When I changed the unit test to:

```
  TRIBITS_ADD_EXECUTABLE_AND_TEST(
    execName
    ...
    ENVIRONMENT env1=envval1 env2=envval2
    WILL_FAIL
    TIMEOUT 11.5
    ADDED_EXE_TARGET_NAME_OUT execName_TARGET_NAME
    ADDED_TESTS_NAMES_OUT execName_TEST_NAME
    )
```
It ended up passing the arguments to TRIBITS_ADD_TEST() in the order:

   ENVIRONMENT env1=envval1 env2=envval2 11.5 WILL_FAIL TIMEOUT
  
which sends the timeout as an ENVIRONMENT argument which seems crazy but is exactly what it is supposed to do (see the documentation for [PARSE_ARGUMENTS()](https://tribits.org/doc/TribitsDevelopersGuide.html#parse-arguments).

The test was trivial to fix.

**Comment by bartlettroscoe** [comment]
Jordan,

I just pushed the following commit to the TriBITS casl-dev repo 'master' branch.  You can go ahead and pull that version.  I am in the process of pushing the change to the github repo (but I also have to push to Trilinos because Trilinos is testing TriBITS right now).  I will put this issue ticket in review after that is complete.

```
commit 437ec3f60576a1804d40dd5fa6934ab0caaaba9d
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Fri Apr 17 11:40:23 2015 -0400

    Fix passing of TIMEOUT as arg not opt in TRIBITS_ADD_EXECUTABLE_AND_TEST() (TriBITS #65)
    
    This fixes a defect in the handling of TIMEOUT in
    TRIBITS_ADD_EXECUTABLE_AND_TEST().  It was handling it as an OPTION (i.e no
    arguments).  There was a unit test but it was worthless because it was testing
    TIMEOUT as an OPTION too!
    
    I updated the unit test to pass in:
    
       TIMEOUT 11.5
    
    instead of just
    
       TIMEOUT
    
    and it showed the defect right away (see TriBITS #65).
    
    It was then trival to fix the bug by changing TIMEOUT handling from an OPTION
    to an ARGUMENT.
    
    Build/Test Cases Summary
    Enabled Packages:
    Enabled all Packages
    0) MPI_RELEASE_DEBUG_SHARED => passed: passed=728,notpassed=0 (38.13 min)
    Other local commits for this build/test group: ee77c81, 48da277
```

**Comment by bartlettroscoe** [comment]
I pushed this commit also to the github repo.  I am putting this issue into review.

Jordan,

Please comment in this ticket once you have verified that the issue is resolved.

Thanks,

-Ross
