### ISSUE TITLE
TriBITS C++11 Detection Does Not Work with Visual Studio

### ISSUE THREAD

**Issue by csiefer2** [TriBITSPub/TriBITS#66]
Modern version of Visual Studio evidently don't use flags any more to enable C++11 support, thus the flag detection in TribitsCXX11Support.cmake will always fail.

Can we fix this?

**Comment by lefebvre** [comment]
Chris,
What version of visual studios?
I'm using 2013 with cl18 and I don't experience any issues.
Thanks,
Jordan

**Comment by csiefer2** [comment]
2010

**Comment by bartlettroscoe** [comment]
As a workaround for this, you could simply just set:

    `-D<Project>_CXX11_FLAGS=" "`

(see [here](https://tribits.org/doc/TribitsBuildQuickRef.html#enabling-support-for-c-11)) and that should avoid the check for the what flags with with C++11.

Actually, it just occurred to me that we could expand the set of flags to check to include the empty string " ".   If the trial C++ program builds with that, then we could use that.

**Comment by csiefer2** [comment]
Works like a champ (at least as far as TriBITS goes), thanks.

**Comment by bartlettroscoe** [comment]
Given that there is a workaround, I will put this in the backlog.  If this becomes an issue for automated testing on Windows (or some other system), we will add the option " " as one of the compiler flags to try to test for C++11 support.

**Comment by bartlettroscoe** [comment]
This problem was also run into by a Trilinos user (see below email).  Therefore, I will go ahead and fix this right away in the current version of TriBITS and snapshot into Trilinos.

-----

From: JR Cary [mailto:cary@colorado.edu] 
Sent: Sunday, May 10, 2015 10:51 AM
To: trilinos-users@trilinos.org
Cc: Bartlett, Roscoe A.
Subject: Problem configuring C++ 11 on Visual Studio 12 (2013) and some mingw fixes in a patch

Thanks.  That helps.

Now I am up to:

C:\winsame\cary\vorpalall-vs12\builds\trilinos-12.0.1\packages\kokkos\core\src\impl\Kokkos_AllocationTracker.cpp(126) : error C3861: 'atomic_fetch_sub': identifier not found

Is Kokkos unix-centric?  Did I invoke its build somehow incorrectly?

BTW, attached is a patch we used to get trilinos to build
with mingw at one point.  I have not tried a mingw build in a while,
however.

...John

On 5/9/15 6:25 PM, Bartlett, Roscoe A. wrote:
Try adding

  -DTrilinos_CXX11_FLAGS=" "

(note the single space).

We will add " " as one of the set of flags to try.

-Ross

________________________________________
From: Trilinos-Users <trilinos-users-bounces@trilinos.org> on behalf of JR Cary <cary@colorado.edu>
Sent: Saturday, May 09, 2015 8:56:03 AM
To: trilinos-users@trilinos.org
Subject: [Trilinos-Users] Problem configuring C++ 11 on Visual Studio 12 (2013) 
 
cmake fails at

CMake Error at cmake/tribits/core/package_arch/TribitsCXX11Support.cmake:148 (MESSAGE):^M
  Error, a set of standard compiler flags cannot be found such that this C++^M
  compiler is able to compile basic C++11 features! Please select a C++^M
  compiler (and compatible compilers for other languages) that supports^M
  C++11.  Or, if this C++ compiler does support C++11 but a special set of^M
  compiler options is needed, then set these flags using^M
  -DTrilinos_CXX11_FLAGS="<c++11-flags>".  Or, if C++11 support in this^M
  project is not needed or desired, then set -DTrilinos_ENABLE_CXX11=OFF.^M
Call Stack (most recent call first):^

But afaik, VS-12 needs no special flags.  So the logic in 
TribitsCXX11Support.cmake of 

      IF ("${${PROJECT_NAME}_CXX11_FLAGS}" STREQUAL "")
      MESSAGE(FATAL_ERROR

will fail, as that variable should be empty for VS12.

Thoughts?

Thanks....John

**Comment by bartlettroscoe** [comment]
This has been pushed to the TriBITS github repo 'master' branch and I snapshotted it to the Trilinos repo as part of the snapshot commit:

```
683ad12 "Automatic snapshot commit from tribits at 99fff71"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Mon May 11 15:50:37 2015 -0400 (13 minutes ago)

M       cmake/tribits/core/package_arch/TribitsCXX11Support.cmake
M       cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake
M       cmake/tribits/python_utils/SnapshotDir.py
```
I am closing this as complete.
