### ISSUE TITLE
CppLint styleguide integration

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#74]
Ross,
I have been pushing code standards within SCALE and I have been playing with cpplint.py.
I have written some TriBITS code which integrates cpplint.
This facilitates style checking on each source and header file for libraries and executables.
What do you think about formally integrating this into TriBITS for all to use.

**Comment by bartlettroscoe** [comment]
Jordan,

I am not sure about TriBITS enforcing the Google coding standard on all C++ code.  For example, Google does not allow C++ exceptions.  But I am supportive of TriBITS facilitating any type of analysis they want for a given TriBITS package or TriBITS Repository wants to impose.  So how would it work?   Would it be run as a custom command at build time automatically?  Would it be a new special target that would be run manually?  How can TriBITS allow TriBITS Packages and TriBITS Repositories to plug in their own special analysis methods?

However, have you considered instead running cpplint.py as a pre-commit hook?  That might be a better place to check for compliance for a coding standard.  You can do this with git for sure as described [here](http://stackoverflow.com/questions/13780700/how-can-i-run-git-pre-commit-checks-only-on-staged-content).  I am sure you can do the same thing with Mercurial.

But whatever we do, it has to be an optional feature on a package-by-package basis and it can't be part of TriBITS Core (which I am trying to keep fairly minimal so people don't balk at the prospect of snapshotting TriBITS Core into their codes).

**Comment by lefebvre** [comment]
Ross,
Cpplint has a number of configuration options which should allow plenty of flexibility with c++ standards for different projects. I envision an optional configuration setting, such as code coverage or memory analysis, which would create custom targets for each source/header for executables/libraries. In this way a developer could enable it and see compile time violations as they are developing. In addition, getting these lint warnings/errors published as build warnings/errors if project/package linting is enabled. I don't have the last part worked out yet, but this would facilitate nightly standards checking.

My complaint with pre-commit hooks is that it is dependent on each developer to initialize them.
My primary goal for SCALE is to publish some sort of standards compliance to CDash , which will initiate discuss at which point we can tweak the standards to the majorities satisfaction.

**Comment by bartlettroscoe** [comment]
Jordan,

In cpplint.py really really fast?  If it is not, then developers will turn it off to speed up the development process.  If it is not sufficiently fast, I would not make it part of the default 'make' targets.  If you do, people will hate you and find ways to turn it off.  If it is slow, you might consider adding a new targets like "make cpplint" or "make <filename>-cpplint" and letting developers run those themselves.  That would be easy to do.  We could provide hooks in TriBITS to allow you to add those types of hooks, at least for starters.

As for the CDash angle, what you really what is a new type of "analysis" like already exists for coverage testing and valgrind testing with CMake/CTest/CDash.  I was talking with Bill Hoffman a while back and he mentioned that they had recently generalized support for an "analysis" with CTest and CDash so that you could add new types of analyses that you could run locally and post to CDash.  I have not used this myself but you might want to ask them about this.

**Comment by lefebvre** [comment]
Ross,
This would be an optional setting, defaulted off. I spoke to a couple of developers and they like the per source file approach. I have a patch ready for TriBITS that you can look over.

**Comment by bartlettroscoe** [comment]
Jordan,

The implementation of this in 7c64363 looks pretty reasonable.  However, it looks like a few more things need to be done before this can be integrated into the mainline:

1. Add a global level option `${PROJECT_NAME}_CPPLINT_SOURCE` that can turn off CPPLINT but let the package-level `${PROJECT_NAME}_CPPLINT_SOURCE` turn it on.  Also, you are going to want advanced cache vars to set `${PROJECT_NAME}_CPPLINT_SOURCE` and set a default based on `${PROJECT_NAME}_CPPLINT_SOURCE`.
1. Consider if you want to the parent package to turn this on or all for all of its subpackages or not.  With the current implementation, if you set `${PROJECT_NAME}_CPPLINT_SOURCE=ON` for the parent package, it will **not** propagate to subpackages.  Is that what you want?
1. Add a section in TribitsDevelopersGuide.rst describing adding cpplint.py checking to a given TriBITS package.  Describe how to customize its usage on a package-by-package basis and how to determine what is checked.  I am guessing this is what the variables `CPPLINT_LINE_LENGTH`, `CPPLINT_STYLE_FILTER`, and `CPPLINT_COUNTING` are for?  Since the functions `CPP_LINT()` and `TRIBITS_LINT_SOURCE()` are never directly called by TriBITS package developers, developers will need a place to find that documentation.  I think the developers guide needs a new section "Code Analysis" and this can go in that section.

Also, a new (optional) subdirectory tribits/analysis/ should be added to put the module file `CppLint.cmake` and then support for this will depend on if this directly exists in the install/snapshot of TriBITS (see #52).  I can see other analysis-related functionality going there at some point.  As I said in an earlier comment, we need to try to actively trim down [TriBITS Core](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-tribits-directory-contents) as much as we can.  To that end, I have already moved out some git-related stuff to other directories.  There is more that I may be able to trim out as well, I will have to see.

How urgent is it to get this into the main TriBITS git 'master' branches on github and casl-dev?  I am going on vacation next week and then the CASL 2.0 meeting is the week after that.  After today, I may not be back at work until the week of July 13.  In the mean-time, can you keep these changes in SCALE's local copy of TriBITS and use it in the mean time?

**Comment by lefebvre** [comment]
Ross,
I'll look into these changes.
As always it would be nice sooner rather then later, but I'll make some changes and whenever you can provide feedback is fine.

Thanks!

**Comment by lefebvre** [comment]
Ross,
My design creates a dependency on CppLint.cmake in core/package_arch/TribitsLibraryMacros.cmake and core/package_arch/TribitsAddExecutable.cmake.

I don't see a way to move CppLint.cmake to the analysis directory while keeping this design.
Do you have any advice?

**Comment by bartlettroscoe** [comment]
Jordan,

You can see an example of doing this in:

    TriBITS/tribits/core/package_arch/TribitsProjectImpl.cmake

in the lines:

```
  SET(TRIBITS_ADD_DASHBOARD_TARGET_MODULE
    ${${PROJECT_NAME}_TRIBITS_DIR}/${TRIBITS_CTEST_DRIVER_DIR}/TribitsAddDashboardTarget.cmake
    )
  IF (
    EXISTS ${TRIBITS_ADD_DASHBOARD_TARGET_MODULE}
    AND
    NOT ${PROJECT_NAME}_TRACE_DEPENDENCY_HANDLING_ONLY
    )
    INCLUDE(${TRIBITS_ADD_DASHBOARD_TARGET_MODULE})
    TRIBITS_ADD_DASHBOARD_TARGET()
  ENDIF()
```

So basically, if that directory was not shapshotted along with TriBITS Core, then support for the `make dashboard` target is not added.  You can do the same thing with CppLint.  If the subdir `analysis/` is not present, then the CppLint features are not present and we only pay a minimal price in increasing the size of the code base in TriBITS Core.

Longer term, I want to find a way to allow a TriBITS project to plug in things like this without having to modify TriBITS Core source code (i.e. the "Open-Closed Principle").  But CMake is a pretty feature-poor programming language so that might be hard to do.

**Comment by lefebvre** [comment]
I am closing this as I do not have time to finish its implementation.
