### ISSUE TITLE
TRIBITS_ADD_EXECUTABLE  argument DIRECTORY changes executable location

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#92]
When using the DIRECTORY argument to specify the directory containing the list of source it has an unexpected consequence in that it compiles the executable in the specified directory.
For now I just specify the absolute source files, removing the DIRECTORY argument.

**Comment by bartlettroscoe** [comment]
Yea, the DIRECTORY arg also changes the location of the executable.  That is just missing in the documentation.  The purpose of the DIRECTORY arg is to allow you to create executables in subdirs from a base CMakeLists.txt file.  I forgot who asked for this feature but there it is.

I will update the documentation to reflect this.

**Comment by bartlettroscoe** [comment]
The update documentation is shown [here](https://tribits.org/doc/TribitsDevelopersGuide.html#formal-arguments-tribits-add-executable).  It says:

"f specified, then the generated executable <exeTargetName> is placed in the relative or absolute directory <dir>. If <dir> is not an absolute path, then the generated executable is placed in the directory ${CMAKE_CURRENT_BINARY_DIR}/<dir>/. Also, the sources for the executable listed in SOURCES <src0> <src1> ... are assumed to be in the relative or absolute directory <dir> instead of the current source directory. This directory path is prepended to each source file name <srci> unless <srci> is an absolute path. If <dir> is not an absolute path, then source files listed in SOURCES are assumed to be in the directory ${CMAKE_CURRENT_SOURCE_DIR}/<dir>/."

That should hopefully make it clear that it also changes the placement of the executable.
